### ISSUE TITLE
Fail to start server on newest update

### ISSUE THREAD

**Issue by Progrsam** [escapingnetwork/core-keeper-dedicated#37] opened 2023-11-29 20:12 UTC
Docker logs:

Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
Logging directory: '/home/steam/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
[  0%] Downloading update...
[  0%] Checking for available updates...
[----] Download complete.
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Cleaning up...
[----] Update complete, launching Steamcmd...
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
Logging directory: '/home/steam/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1700160359
-- type 'quit' to exit --
Loading Steam API...OK

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x61) downloading, progress: 19.90 (14680064 / 73781292)
 Update state (0x81) verifying update, progress: 78.05 (57587964 / 73781292)
Success! App '1007' fully installed.
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x61) downloading, progress: 19.38 (89537616 / 462089057)
 Update state (0x61) downloading, progress: 33.66 (155531618 / 462089057)
 Update state (0x61) downloading, progress: 52.45 (242383802 / 462089057)
 Update state (0x61) downloading, progress: 73.14 (337983627 / 462089057)
 Update state (0x61) downloading, progress: 89.90 (415418188 / 462089057)
 Update state (0x81) verifying update, progress: 31.62 (146091002 / 462089057)
Success! App '1963720' fully installed.
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
Logging directory: '/home/steam/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1700160359
-- type 'quit' to exit --
Loading Steam API...OK

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
Success! App '1007' already up to date.
Success! App '1963720' already up to date.
xvinfo:  Unable to open display :99
Failed to start Xvfb, retry: 1
_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
X-Video Extension version 2.2
screen #0
 no adaptors present
-batchmode -logfile CoreKeeperServerLog.txt -world 0 -worldname 3DevBros Core Keeper Server -worldseed 0 -worldmode 0 -datapath /home/steam/core-keeper-data -maxplayers 10 -season -1
Started server process with pid 134
[UnityMemory] Configuration Parameters - Can be set up in boot.config
    "memorysetup-bucket-allocator-granularity=16"
    "memorysetup-bucket-allocator-bucket-count=8"
    "memorysetup-bucket-allocator-block-size=4194304"
    "memorysetup-bucket-allocator-block-count=1"
    "memorysetup-main-allocator-block-size=16777216"
    "memorysetup-thread-allocator-block-size=16777216"
    "memorysetup-gfx-main-allocator-block-size=16777216"
    "memorysetup-gfx-thread-allocator-block-size=16777216"
    "memorysetup-cache-allocator-block-size=4194304"
    "memorysetup-typetree-allocator-block-size=2097152"
    "memorysetup-profiler-bucket-allocator-granularity=16"
    "memorysetup-profiler-bucket-allocator-bucket-count=8"
    "memorysetup-profiler-bucket-allocator-block-size=4194304"
    "memorysetup-profiler-bucket-allocator-block-count=1"
    "memorysetup-profiler-allocator-block-size=16777216"
    "memorysetup-profiler-editor-allocator-block-size=1048576"
    "memorysetup-temp-allocator-size-main=4194304"
    "memorysetup-job-temp-allocator-block-size=2097152"
    "memorysetup-job-temp-allocator-block-size-background=1048576"
    "memorysetup-job-temp-allocator-reduction-small-platforms=262144"
    "memorysetup-allocator-temp-initial-block-size-main=262144"
    "memorysetup-allocator-temp-initial-block-size-worker=262144"
    "memorysetup-temp-allocator-size-background-worker=32768"
    "memorysetup-temp-allocator-size-job-worker=262144"
    "memorysetup-temp-allocator-size-preload-manager=262144"
    "memorysetup-temp-allocator-size-nav-mesh-worker=65536"
    "memorysetup-temp-allocator-size-audio-worker=65536"
    "memorysetup-temp-allocator-size-cloud-worker=32768"
    "memorysetup-temp-allocator-size-gfx=262144"
./launch.sh: line 80:   134 Segmentation fault      (core dumped) DISPLAY=:99 LD_LIBRARY_PATH="$LD_LIBRARY_PATH:../Steamworks SDK Redist/linux64/" ./CoreKeeperServer "${params[@]}"

**Comment by Micke90s** [comment] 2023-11-29 20:55
I can reproduce the error on my Linux host (Debian GNU/Linux 12 (bookworm)) for new containers. 
The old container which already exist (and only updated the steam components) seems to run. (I only joined the server and did not check if the infinite generation of the world works)

**Comment by Micke90s** [comment] 2023-12-04 21:08
@Progrsam: Core Kepper released the patch [0.7.2.1](https://store.steampowered.com/news/app/1621690/view/5458988598265629529). Seems that this patch solves the problem. Could you please give it a try on your system.

**Comment by Micke90s** [comment] 2023-12-05 07:39
@Progrsam Could you please try to run a new container? At startup the container pulls the latest version of the game from steam. But also, I got the problem that my old container was running correct after restart while the new container which also should use the same version did not work. So, I am not sure if there are any old components of the previous version remains.

The CoreKeeperServerLog.txt seems to contain the current version:
```
Checking system requirements: PASS
Manager prelaunch and GO initialization starting...
Core count is 8
Job worker count is 7
Version: 0.7.2.1-008c
Skipping faction mod /home/steam/core-keeper-dedicated/CoreKeeperServer_Data/StreamingAssets/Conf/Factions/None.json with
faction None (0)
Skipping loot mod /home/steam/core-keeper-dedicated/CoreKeeperServer_Data/StreamingAssets/Conf/Loot/Empty.json for loot ta
ble Empty (0)
Found 281 converter(s) and 3 post-converter(s)
PugDatabase initialized 2108 prefabs
Forcing season -1
```
You can enter the container by using the `docker exec` comand
`docker exec -it <NameOfContainer> /bin/bash`
e.g.
`docker exec -it corekeeper /bin/bash`

To show the logs in the container just run:
`more ./core-keeper-dedicated/CoreKeeperServerLog.txt`

**Comment by Progrsam** [comment] 2023-12-05 13:23
I setup a new container and also still have the same error. Also my log does not contain the game version somehow. Maybe because it crashes before?

**Comment by Micke90s** [comment] 2023-12-05 14:32
@arguser I just created a new container on the linux host. On update 0.7.2 the error occurred. After Patch 0.7.2.1 creating a new container is working. No changes on the host.

Unfortunately, I do not know what was changed in detail. 
On 0.7.2 I tried to:
* build the docker image from the Dockerfile directly on the Linux host
* checked dependencies of the CoreKeeperServer application
* updated the Linux programs inside of the container (via `apt-get`)

Nothing worked. 
After the update to 0.7.2.1 I only started a new container via `docker run` and everything worked again.

Sorry that´s all I got at the moment.

**Comment by TerrifiedBug** [comment] 2024-03-21 20:08
I am also getting this issue.

version: "3"

services:
  core-keeper:
    container_name: corekeeper-server
    image: escaping/core-keeper-dedicated
    volumes:
      - ./data/server-files:/home/steam/core-keeper-dedicated
      - ./data/server-data:/home/steam/core-keeper-data
    environment:
      WORLD_INDEX: "0"
      WORLD_NAME: "Core Keeper Server"
      WORLD_SEED: "0"
      WORLD_MODE: "0"
      GAME_ID:
      DATA_PATH: "/home/steam/core-keeper-data"
      MAX_PLAYERS: "8"
      DISCORD: "1"
      DISCORD_HOOK: "https://discord.com/api/webhooks/XXX"
      SEASON: "-1"
      SERVER_IP: ""
      SERVER_PORT: ""
    restart: unless-stopped
    #stop_grace_period: 2m

Log file:

Loading Steam API...OK
Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
Success! App '1007' already up to date.
Success! App '1963720' already up to date.
xvinfo:  Unable to open display :99
Failed to start Xvfb, retry: 1
_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
X-Video Extension version 2.2
      
0
 no adaptors present
-batchmode -logfile CoreKeeperServerLog.txt -world 0 -worldname Da Boiz Core Keeper Server -worldseed 0 -worldmode 0 -datapath /home/steam/core-keeper-data -maxplayers 8 -season -1
Started server process with pid 90
[UnityMemory] Configuration Parameters - Can be set up in boot.config
    "memorysetup-bucket-allocator-granularity=16"
    "memorysetup-bucket-allocator-bucket-count=8"
    "memorysetup-bucket-allocator-block-size=4194304"
    "memorysetup-bucket-allocator-block-count=1"
    "memorysetup-main-allocator-block-size=16777216"
    "memorysetup-thread-allocator-block-size=16777216"
    "memorysetup-gfx-main-allocator-block-size=16777216"
    "memorysetup-gfx-thread-allocator-block-size=16777216"
    "memorysetup-cache-allocator-block-size=4194304"
    "memorysetup-typetree-allocator-block-size=2097152"
    "memorysetup-profiler-bucket-allocator-granularity=16"
    "memorysetup-profiler-bucket-allocator-bucket-count=8"
    "memorysetup-profiler-bucket-allocator-block-size=4194304"
    "memorysetup-profiler-bucket-allocator-block-count=1"
    "memorysetup-profiler-allocator-block-size=16777216"
    "memorysetup-profiler-editor-allocator-block-size=1048576"
    "memorysetup-temp-allocator-size-main=4194304"
    "memorysetup-job-temp-allocator-block-size=2097152"
    "memorysetup-job-temp-allocator-block-size-background=1048576"
    "memorysetup-job-temp-allocator-reduction-small-platforms=262144"
    "memorysetup-allocator-temp-initial-block-size-main=262144"
    "memorysetup-allocator-temp-initial-block-size-worker=262144"
    "memorysetup-temp-allocator-size-background-worker=32768"
    "memorysetup-temp-allocator-size-job-worker=262144"
    "memorysetup-temp-allocator-size-preload-manager=262144"
    "memorysetup-temp-allocator-size-nav-mesh-worker=65536"
    "memorysetup-temp-allocator-size-audio-worker=65536"
    "memorysetup-temp-allocator-size-cloud-worker=32768"
    "memorysetup-temp-allocator-size-gfx=262144"
./launch.sh: line 80:    90 Segmentation fault      (core dumped) DISPLAY=:99 LD_LIBRARY_PATH="$LD_LIBRARY_PATH:../Steamworks SDK Redist/linux64/" ./CoreKeeperServer "${params[@]}"

**Comment by arguser** [comment] 2024-03-23 17:00
> @arguser I just created a new container on the linux host. On update 0.7.2 the error occurred. After Patch 0.7.2.1 creating a new container is working. No changes on the host.
> 
> Unfortunately, I do not know what was changed in detail. On 0.7.2 I tried to:
> 
>     * build the docker image from the Dockerfile directly on the Linux host
> 
>     * checked dependencies of the CoreKeeperServer application
> 
>     * updated the Linux programs inside of the container (via `apt-get`)
> 
> 
> Nothing worked. After the update to 0.7.2.1 I only started a new container via `docker run` and everything worked again.
> 
> Sorry that´s all I got at the moment.

I've been successfully starting a server on one of my laptops, the one I use for servers which is older is not being able to run it. Going to dig deeper.

**Comment by Progrsam** [comment] 2024-03-23 18:59
@arguser Ah yes, deleting the WORLD_INDEX and WORLD_SEED fixed it for me. Thanks a lot

**Comment by Micke90s** [comment] 2024-09-04 20:50
@arguser This seems to be solved. Could you please close this issuer?

**Closed** 2024-09-04 20:52 UTC
